export const LAWAREA_DATA = [
  {
    id: 1,
    name: 'Family Law',
    areas: [
      { id: 1, name: 'Divorce Law' },
      { id: 2, name: 'Civil Disputes & Litigation' },
      { id: 3, name: 'Family / Matrimonial' },
      { id: 4, name: 'Children' },
      { id: 5, name: 'Child Care' },
    ],
  },
  {
    id: 2,
    name: 'Criminal Law',
    areas: [
      { id: 6, name: 'Fraud, White Collar, Business & Serious Crime' },
      { id: 7, name: 'Criminal Defence' },
      { id: 8, name: 'Advocacy & Appeals' },
      { id: 9, name: 'Confiscation, Restraint & Cash Forfeiture' },
      { id: 10, name: 'Road Traffic & Driving Offences' },
      { id: 11, name: 'Terrorism' },
      { id: 12, name: 'Courts Martial & Military Law' },
      { id: 13, name: 'Criminal' },
      { id: 14, name: 'Criminal Law & Criminal Defence' },
      { id: 15, name: 'Motoring' },
    ],
  },
  {
    id: 3,
    name: 'Property Law',
    areas: [
      { id: 16, name: 'Residential Property Conveyancing' },
      { id: 17, name: 'Equity Release' },
      { id: 18, name: 'Residential Property Disputes' },
      { id: 19, name: 'Landlord and Tenant (Commercial and Domestic)' },
      { id: 20, name: 'Probate and Estate Administration' },
      { id: 21, name: 'Commercial Property' },
      { id: 22, name: 'Residential Conveyancing' },
      { id: 23, name: 'Landlord & Tenant Disputes' },
    ],
  },
  {
    id: 4,
    name: 'Employment Law',
    areas: [
      { id: 24, name: 'Health & Safety Law' },
      { id: 25, name: 'Pensions & Incentives' },
      { id: 26, name: 'Employment Law Settlement Agreement' },
      { id: 27, name: 'Employment Law' },
      { id: 28, name: 'Employment For Businesses' },
    ],
  },
  {
    id: 5,
    name: 'Wills and Probate',
    areas: [
      {
        id: 29,
        name: 'Wills, Trusts and Tax Planning',
      },
    ],
  },
  {
    id: 6,
    name: 'Personal Injury Law',
    areas: [
      { id: 30, name: 'Clinical Negligence' },
      { id: 31, name: 'Personal Injury' },
      { id: 32, name: 'Medical And Clinical Negligence' },
      { id: 33, name: 'Sport' },
    ],
  },
  {
    id: 7,
    name: 'Contract Law',
  },
  {
    id: 8,
    name: 'Immigration Law',
    areas: [
      { id: 34, name: 'Immigration (Privately Paid)' },
      { id: 35, name: 'Extradition & Mutual Assistance' },
      { id: 36, name: 'Immigration' },
      { id: 37, name: 'Nationality' },
      { id: 38, name: 'Asylum' },
      { id: 40, name: 'Leave to Remain' },
      { id: 41, name: 'Entry Clearance' },
      { id: 42, name: 'Spouse Visa' },
      { id: 43, name: 'Adult Dependant Relative' },
      { id: 44, name: 'Article 8' },
      { id: 45, name: 'European Free Movement' },
      { id: 46, name: 'Residence Cards' },
      { id: 47, name: 'EEA Regulations' },
      { id: 48, name: 'Family based applications' },
      { id: 49, name: 'Naturalisation' },
      { id: 50, name: 'Registration' },
      { id: 51, name: 'Stateless' },
      { id: 52, name: 'First-tier Tribunal Appeals' },
      { id: 53, name: 'Upper Tribunal Appeals' },
      { id: 54, name: 'Long Residence' },
      { id: 55, name: 'Points Based System' },
      { id: 56, name: 'Sponsorship Licence' },
      { id: 57, name: 'Student Visas' },
      { id: 58, name: 'Entrepreneurs Visas' },
      { id: 59, name: 'Intra Company Transfers' },
      { id: 60, name: 'Humanitarian Protection' },
      { id: 61, name: 'Discretionary Leave' },
      { id: 62, name: 'International Protection' },
    ],
  },
  {
    id: 9,
    name: 'Commercial Law',
    areas: [
      { id: 63, name: 'Planning Law' },
      { id: 64, name: 'Tax Law' },
      { id: 65, name: 'Aviation' },
      { id: 66, name: 'Business Debt Recovery Services' },
      { id: 67, name: 'Business Defence' },
      { id: 68, name: 'Business Insolvency Service' },
      { id: 69, name: 'Pub And Brewery Services' },
      { id: 70, name: 'Corporate And Commercial Law' },
      { id: 71, name: 'Professional Negligence' },
      { id: 72, name: 'Commercial Leases' },
    ],
  },
  { id: 10, name: 'Intellectual Property Law' },
  { id: 11, name: 'Bankruptcy and Insolvency Law' },
  {
    id: 12,
    name: 'Human Rights Law',
    areas: [{ id: 73, name: 'Human Rights' }],
  },
  {
    id: 13,
    name: 'Administrative and Regulatory Law',
    areas: [{ id: 74, name: 'Regulatory Enforcement & Disciplinary' }],
  },
  {
    id: 14,
    name: 'Private Client Services',
    areas: [
      { id: 75, name: 'Travel' },
      { id: 76, name: 'Insurance' },
      { id: 77, name: 'Will Writing Services' },
      { id: 78, name: 'Lasting Powers Of Attorney (Lpa)' },
      { id: 79, name: 'Trusts' },
      { id: 80, name: 'Estate Planning' },
      { id: 81, name: 'Probate And Estate Administration' },
      { id: 82, name: 'Contentious Probate' },
      { id: 83, name: 'Will, Trust & Estate Disputes' },
    ],
  },
  {
    id: 15,
    name: 'Litigation Law',
    areas: [
      { id: 84, name: 'Litigation - Other' },
      { id: 85, name: 'Dispute Resolution' },
      { id: 86, name: 'Contentious Probate' },
      { id: 87, name: 'Civil Litigation' },
    ],
  },
  {
    id: 16,
    name: 'Domestic Voilence',
    areas: [
      { id: 1, name: 'Phycical Abuse' },
      { id: 2, name: 'Protection notice order' },
      { id: 3, name: 'Domestic violence' },
      { id: 4, name: 'Child Care' },
    ],
  },
];
