export const SEARCH_DATA = [
  {
    qn: 'What steps are typically taken when reporting physical abuse to the authorities?',
    an: 'In the UK, if someone experiences physical abuse in a domestic situation, there are several important steps to take. First and foremost, ensuring the victims safety is paramount, so if there is an immediate threat, it is crucial to call emergency services 999 for police assistance. Afterward, getting in touch with the local police station is essential to report the abuse, providing a detailed account of what happened along with any evidence. Seeking medical attention for any injuries is also important, and keeping any evidence like photos or messages can be helpful. Victims can explore legal options, such as getting a restraining order, cooperating with the police to press charges, and potentially being part of court proceedings. Support services like Womens Aid are there to provide guidance and shelter if needed, and counseling or therapy can help address the emotional impact. Remember, the process might differ depending on where you are, and it is always a good idea to seek advice from professionals who can provide the most up-to-date information and support.',
    topic: { id: 1, name: 'Phycical Abuse' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'How can someone legally protect themselves from an abusive partner and obtain a protective order?',
    an: 'To legally protect oneself from an abusive partner and obtain a protective order, one can apply for a non-molestation order or an occupation order. The process involves submitting evidence and attending court proceedings. These protective orders can prevent the abusive partner from contacting the individual or entering their home. After applying, the court will review the evidence and make a decision. The duration of the protective order can vary, and any violations can lead to legal consequences. If modifications or extensions are needed, it is advisable to consult legal professionals and follow the appropriate court procedures.',
    topic: { id: 1, name: 'Phycical Abuse' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'What steps should be taken to gather evidence after experiencing physical abuse?',
    an: 'To gather evidence after experiencing physical abuse, it is essential to collect various types of evidence, including photographs, medical records, text messages, and witness statements. Document incidents by noting dates, times, and locations. Legal aid may be available, so consult legal professionals or support organizations for guidance on accessing it. Seek support and advice on securely preserving evidence. Text messages and emails are admissible as evidence. Witness statements should be detailed and include dates and times of observations. Safely preserve evidence digitally or in secure locations. Medical records can be valuable in court. Consult professionals for assistance with accessing legal aid and gathering evidence.',
    topic: { id: 1, name: 'Phycical Abuse' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'What is a Protection notice order',
    an: 'A protection notice order is a type of order that can be issued by the police or the courts to protect a person from domestic abuse. It can prohibit or require the abuser to do certain things, such as leaving the home or attending a behaviour change programme. A protection notice order is also known as a domestic abuse protection notice (DAPN) or a domestic abuse protection order (DAPO).',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'How to get a protection notice order',
    an: 'To get a protection notice order, you can apply to the family court, unless you are in Scotland, where you can apply to the sheriff court. You can also ask the police, a specified third party (such as a charity or a local authority), or any other person with the leave of the court to apply for a protection notice order on your behalf. If the police give you a DAPN, they must apply for a DAPO within 48 hours.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'What grounds I will get a protection notice order',
    an: 'You will get a protection notice order if the court is satisfied that there are reasonable grounds to believe that you have been abused by a person who is personally connected to you, and that it is necessary and proportionate to make the order to protect you from further abuse. The court will consider the nature and extent of the abuse, the harm caused or likely to be caused by it, and your wishes and feelings.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'How to obtain a protection notice order',
    an: 'To obtain a protection notice order, you will need to provide evidence of the abuse and its impact on you. You may also need to attend a hearing where the court will hear from both you and the abuser. The court may make an interim order while it decides on the final order.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'How long does it take to get protection notice order approved by the court',
    an: 'The time it takes to get a protection notice order approved by the court depends on various factors, such as the urgency of your situation, the availability of the court, and whether there are any disputes or appeals. It may take from a few days to several weeks or months. If you need immediate protection, you can ask for an emergency order or contact the police.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'Apply for protection notice order self',
    an: 'You will need to fill out an application form and a witness statement, explaining why you need the order and what you want the order to do. You can find the forms online at or at your local family court.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'Apply for protection notice order by police officer',
    an: 'You will need to take your completed forms and any supporting evidence (such as photos, medical reports, police reports, etc.) to the family court. You will also need to pay a fee of £155, unless you are eligible for a fee remission.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'Who can apply for a Protection Notice Order',
    an: 'You will need to attend a hearing where the court will decide whether to grant you the order or not. The court may make an interim order while it decides on the final order. The court will also notify the person you want to be protected from (the respondent) about your application and the hearing date.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'When can a Protection Notice Order be issued?',
    an: 'If the court grants you the order, you will need to serve a copy of the order on the respondent as soon as possible. You can ask the court bailiff or a process server to do this for you, or you can do it yourself if it is safe for you to do so. You will also need to keep a copy of the order with you at all times and report any breaches of the order to the police.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'What happens after a Protection Notice Order is issued?',
    an: 'Once a Protection Notice Order (PNO) is issued, the police will serve it to the abuser. The abuser will be told not to contact or harm the person at risk. If the order is breached, the police can take further action.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'Can the person at risk request a Protection Notice Order?',
    an: 'The person at risk cannot directly request a Protection Notice Order (PNO). However, they can report the abuse to the police, and if the police believe there is a risk, they can issue the order for protection.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'How long does a Protection Notice Order last?',
    an: 'A Protection Notice Order (PNO) is temporary and lasts for a short period, usually up to 48 hours. During this time, the situation is assessed, and further measures can be taken for ongoing protection if needed.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'What happens if the abuser violates a Protection Notice Order?',
    an: 'If the abuser breaks the rules of a Protection Notice Order (PNO), the police can take action against them. This might include arresting the abuser and bringing them to court for not following the order. The consequences for violating the order are explained in the Domestic Abuse Act 2021, Part 3, Section 27.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'Can the person at risk appeal a Protection Notice Order?',
    an: 'Can the person at risk appeal a Protection Notice Order? The person at risk can appeal a Protection Notice Order if they think it is not necessary or proportionate to protect them from the abuser. They can appeal to a magistrates court within 21 days of being issued with the notice. While the appeal is in progress a requirement imposed by the notice to stop doing specified things remains in effect, unless the court orders otherwise.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'Are there any restrictions placed on the person at risk by a Protection Notice Order?',
    an: 'Are there any restrictions placed on the person at risk by a Protection Notice Order? A Protection Notice Order does not place any restrictions on the person at risk, but only on the abuser. However, all Protection Notice Orders carry notification requirements requiring the person subject to the order to notify the police of their name and home address and of any changes to this information, thereby assisting the police to monitor the perpetrators whereabouts and the risk they pose to the victim.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'How is a Protection Notice Order different from a restraining order?',
    an: 'A Protection Notice Order is different from a restraining order in several ways. First, a Protection Notice Order can be issued by the police or the courts, while a restraining order can only be issued by the courts. Second, a Protection Notice Order can be issued for any criminal offence, while a restraining order can only be issued for offences involving harassment or fear of violence. Third, a Protection Notice Order can impose both prohibitions and positive requirements on the abuser, such as attending a behaviour change programme, while a restraining order can only impose prohibitions, such as staying away from the victim.',
    topic: { id: 2, name: 'Protection notice order' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'What is domestic voilence?',
    an: 'According to the Domestic Abuse Act 2021, domestic abuse is defined as any incident or pattern of incidents of controlling, coercive, threatening behaviour, violence or abuse between those aged 16 or over who are, or have been, intimate partners or family members, regardless of gender or sexuality . The abuse can encompass, but is not limited to: physical abuse, emotional abuse, psychological abuse, sexual abuse, economic abuse. The Act also recognises that children can be victims of domestic abuse, either by witnessing it or by being subject to it themselves . The Act aims to provide better protection and support for victims and survivors of domestic abuse and to hold perpetrators accountable for their actions.',
    topic: { id: 3, name: 'Domestic violence' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
  {
    qn: 'What are the different types of domestic abuse',
    an: 'The Domestic Abuse Act 2021 recognizes Five different types of domestic abuse, which are: (a)  physical or sexual abuse, (b)  violent or threatening behaviour (c)  controlling or coercive behaviour; (d)  economic abuse (see subsection (4)), (e)  psychological, emotional or other abuse. These types of domestic abuse can occur separately or together. They can also vary in frequency and severity. The Domestic Abuse Act 2021 aims to provide a clear and consistent definition of domestic abuse that covers all its forms and effects.',
    topic: { id: 3, name: 'Domestic violence' },
    area: { id: 16, name: 'Domestic Voilence' },
  },
];
