export const SOLICITOR_DATA = [
  
  {
    title: 'Shahban Law Limited Trading Names',
    AuthorisationDate: '2014-11-01T00:00:00',
    SRAID: '8003856',
    Tel: '01782 272777',
    email: 'info@shahbansolicitors.com',
    web: 'https://www.shahbansolicitors.com',
    address: {
      buliding: '11 Birch Terrace',
      town: 'Stoke-On-Trent',
      postcode: 'ST1 3JN',
      country: 'England',
    },
    branch: '2',
    solicitors: '6',
    accreditations: [
          {
        id: 'acc2',
        txt: 'Higher courts rights – civil',
      },
      {
        id: 'acc3',
        txt: 'Higher courts rights – criminal',
      },
      {
        id: 'acc4',
        txt: 'Lexcel Practice Management Standard accreditation',
      },
      {
        id: 'acc1',
        txt: 'Criminal Litigation accreditation',
      },
    ],
    area: [
      { id: 13, name: 'Criminal' },
      { id: 31, name: 'Personal Injury' },
      { id: 15, name: 'Motoring' },
      { id: 36, name: 'Immigration' },
      { id: 23, name: 'Landlord & Tenant Disputes' },
      { id: 87, name: 'Civil Litigation' },
      { id: 3, name: 'Family / Matrimonial' },
      { id: 72, name: 'Commercial Leases' },
      { id: 88, name: 'Domestic Voilence' },
    ],
  },
  {
    title: 'Tuckers Solicitors Llp',
    AuthorisationDate: '2001-11-01T00:00:00',
    SRAID: '628234',
    Tel: '01782608738',
    web: 'https://www.tuckerssolicitors.com',
    email: 'tuckers@tuckerssolicitors.com',
    address: {
      buliding: 'DX 14451',
      town: 'Manchester',
      postcode: 'Manchester 2',
      country: 'England',
    },
    branch: '22',
    solicitors: '88',
    accreditations: [
      { id: 'acc1', txt: 'Criminal Litigation accreditation' },
      {
        id: 'acc5',
        txt: 'Mental health',
      },
      {
        id: 'acc2',
        txt: 'Higher courts rights – civil',
      },

      {
        id: 'acc3',
        txt: 'Higher courts rights – criminal',
      },
      {
        id: 'acc4',
        txt: 'Lexcel Practice Management Standard accreditation',
      },
    ],
    area: [
      { id: 6, name: 'Fraud, White Collar, Business & Serious Crime' },
      { id: 7, name: 'Criminal Defence' },
      { id: 8, name: 'Advocacy & Appeals' },
      { id: 9, name: 'Confiscation, Restraint & Cash Forfeiture' },
      { id: 10, name: 'Road Traffic & Driving Offences' },
      { id: 11, name: 'Terrorism' },
      { id: 12, name: 'Courts Martial & Military Law' },
      { id: 35, name: 'Extradition & Mutual Assistance' },
      { id: 34, name: 'Immigration (Privately Paid)' },
      { id: 74, name: 'Regulatory Enforcement & Disciplinary' },
      { id: 24, name: 'Health & Safety Law' },
      { id: 88, name: 'Domestic Voilence' },
    ],
  },
  {
    title: 'SMK Solicitors',
    AuthorisationDate: '2002-11-01T00:00:00',
    SRAID: '8003883',
    Tel: '01782 213 666',
    web: 'http://smksolicitors.co.uk/',
    email: 'info@smksolicitors.co.uk',
    address: {
      buliding: 'Smk House, 31-33 Albion Street',
      town: 'Stoke On Trent',
      postcode: 'ST1 1QF',
      country: 'England',
    },
    branch: '2',
    solicitors: '3',
    accreditations: [],
    area: [
      { id: 34, name: 'Immigration (Privately Paid)' },
      { id: 35, name: 'Extradition & Mutual Assistance' },
      { id: 36, name: 'Immigration' },
      { id: 37, name: 'Nationality' },
      { id: 38, name: 'Asylum' },
      { id: 39, name: 'Human Rights' },
      { id: 40, name: 'Leave to Remain' },
      { id: 41, name: 'Entry Clearance' },
      { id: 42, name: 'Spouse Visa' },
      { id: 43, name: 'Adult Dependant Relative' },
      { id: 44, name: 'Article 8' },
      { id: 45, name: 'European Free Movement' },
      { id: 46, name: 'Residence Cards' },
      { id: 47, name: 'EEA Regulations' },
      { id: 48, name: 'Family based applications' },
      { id: 49, name: 'Naturalisation' },
      { id: 50, name: 'Registration' },
      { id: 51, name: 'Stateless' },
      { id: 52, name: 'First-tier Tribunal Appeals' },
      { id: 53, name: 'Upper Tribunal Appeals' },
      { id: 54, name: 'Long Residence' },
      { id: 55, name: 'Points Based System' },
      { id: 56, name: 'Sponsorship Licence' },
      { id: 57, name: 'Student Visas' },
      { id: 58, name: 'Entrepreneurs Visas' },
      { id: 59, name: 'Intra Company Transfers' },
      { id: 60, name: 'Humanitarian Protection' },
      { id: 61, name: 'Discretionary Leave' },
      { id: 62, name: 'International Protection' },
      { id: 88, name: 'Domestic Violence' },
    ],
  },
  {
    title: '360 LAW SERVICES LIMITED',
    AuthorisationDate: '2010-04-01T00:00:00',
    SRAID: '638684',
    Tel: '03337727736',
    web: 'http://www.360lawservices.com/',
    email: '',
    address: {
      buliding: 'Base Point Business Centre, 377-399 London Road, Camberley',
      town: 'Surrey',
      postcode: 'GU15 3HL',
      country: 'England',
    },
    branch: '1',
    solicitors: '37',
    accreditations: [
      {
        id: 'acc2',
        txt: 'Higher courts rights – civil',
      },
      {
        id: 'acc3',
        txt: 'Higher courts rights – criminal',
      },
      {
        id: 'acc6',
        txt: 'Conveyancing Quality Scheme accreditation',
      },
    ],
    area: [
      { id: 3, name: 'Family / Matrimonial' },
      { id: 1, name: 'Divorce Law' },
      { id: 2, name: 'Civil Disputes & Litigation' },
      { id: 30, name: 'Clinical Negligence' },
      { id: 31, name: 'Personal Injury' },
      { id: 27, name: 'Employment Law' },
      { id: 25, name: 'Pensions & Incentives' },
      { id: 36, name: 'Immigration' },
      { id: 73, name: 'Human Rights' },
      { id: 75, name: 'Travel' },
      { id: 76, name: 'Insurance' },
      { id: 88, name: 'Domestic Voilence' },
    ],
  },
  {
    title: 'JAMES MURRAY SOLICITORS',
    AuthorisationDate: '2008-11-01T00:00:00',
    SRAID: '74277',
    Tel: '01519333333',
    web: 'http://www.jamesmurraylaw.com/',
    email: 'info@jamesmurraylaw.com',
    address: {
      buliding: '41 Merton Road',
      town: 'BOOTLE',
      postcode: 'L20 7AP',
      country: 'England',
    },
    branch: '12',
    solicitors: '112',
    accreditations: [
      {
        id: 'acc7',
        txt: 'Childrens Representative accreditation',
      },
      {
        id: 'acc8',
        txt: 'Family Representative accreditation',
      },
      {
        id: 'acc2',
        txt: 'Higher courts rights – criminal accreditation',
      },
    ],

    area: [
      { id: 84, name: 'Litigation - Other' },
      { id: 19, name: 'Landlord and Tenant (Commercial and Domestic)' },
      { id: 13, name: 'Criminal' },
      { id: 3, name: 'Family / Matrimonial' },
      { id: 29, name: 'Wills, Trusts and Tax Planning' },
      { id: 4, name: 'Children' },
      { id: 31, name: 'Personal Injury' },
      { id: 20, name: 'Probate and Estate Administration' },
      { id: 88, name: 'Domestic Voilence' },
    ],
  },
  {
    title: 'DEWAR HOGAN',
    AuthorisationDate: '2010-02-01T00:00:00',
    SRAID: '74291',
    Tel: '02078326410',
    web: 'http://www.dewarhogan.co.uk/',
    email: 'info@dewarhogan.co.uk',
    address: {
      buliding: '70 Pall Mall',
      town: 'London',
      postcode: 'SW1Y 5ES',
      country: 'England',
    },
    branch: '1',
    solicitors: '2',
    accreditations: [],
    area: [
      { id: 84, name: 'Litigation - Other' },
      { id: 19, name: 'Landlord And Tenant (Commercial and Domestic)' },
    ],
  },
  {
    title: 'SMITHS (SOLICITORS) LLP',
    AuthorisationDate: '2011-11-01T00:00:00',
    SRAID: '640878',
    Tel: '01782324454',
    web: 'https://smithpartnership.co.uk/',
    email: 'info@smithpartnership.co.uk',
    address: {
      buliding: '88-90 The Strand',
      town: 'Stoke-On-Trent',
      postcode: 'ST3 2PB',
      country: 'England',
    },
    branch: '5',
    solicitors: '62',
    accreditations: [
      {
        id: 'acc1',
        txt: 'Criminal Litigation accreditation',
      },
      {
        id: 'acc4',
        txt: 'Lexcel Practice Management Standard accreditation',
      },
      {
        id: 'acc6',
        txt: 'Conveyancing Quality Scheme accreditation',
      },
      {
        id: 'acc7',
        txt: 'Childrens Representative accreditation',
      },
      {
        id: 'acc8',
        txt: 'Family Representative accreditation',
      },
      {
        id: 'acc9',
        txt: 'Family Advanced accreditation',
      },
      {
        id: 'acc10',
        txt: 'Personal Injury accreditation',
      },
    ],
    area: [
      { id: 84, name: 'Litigation - Other' },
      { id: 19, name: 'Landlord And Tenant (Commercial and Domestic)' },
      { id: 65, name: 'Aviation' },
      { id: 66, name: 'Business Debt Recovery Services' },
      { id: 67, name: 'Business Defence' },
      { id: 68, name: 'Business Insolvency Service' },
      { id: 5, name: 'Child Care' },
      { id: 21, name: 'Commercial Property' },
      { id: 82, name: 'Contentious Probate' },
      { id: 70, name: 'Corporate And Commercial Law' },
      { id: 14, name: 'Criminal Law & Criminal Defence' },
      { id: 85, name: 'Dispute Resolution' },
      { id: 26, name: 'Employment Law Settlement Agreement' },
      { id: 27, name: 'Employment Law' },
      { id: 28, name: 'Employment For Businesses' },
      { id: 3, name: 'Family / Matrimonial' },
      { id: 19, name: 'Landlord and Tenant (Commercial and Domestic)' },
      { id: 32, name: 'Medical And Clinical Negligence' },
      { id: 15, name: 'Motoring' },
      { id: 31, name: 'Personal Injury' },
      { id: 33, name: 'Sport' },
      { id: 88, name: 'Domestic Voilence' },
    ],
  },
];
